# Entwicklungscontainer
FROM node:18

WORKDIR /APP

# Installiere Abhängigkeiten
COPY package.json package-lock.json ./

RUN npm install

# Kopiere den gesamten Code
COPY . /APP

# Setze die Berechtigungen auf alle Dateien im Verzeichnis /APP
RUN chmod -R 755 /APP

# Exponiere den Entwicklungsserver-Port
EXPOSE 4200

# Starte den Entwicklungsserver im Watch-Modus
CMD ["npm", "start"]
